image: simgrid/stable

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test-git:
  script:
  - apt-get update
  - apt-get install -y cmake build-essential libboost-dev
  - cmake .
  - make VERBOSE=1
  - ctest

 