image: simgrid/stable

test-git:
  script:
  - apt-get update
  - apt-get install -y cmake build-essential libboost-dev
  - mkdir -p deps; git clone --depth=1 //git.code.sf.net/p/fmipp/code deps/fmipp 
  - cmake .
  - make VERBOSE=1
  - ctest

 